### ISSUE TITLE
请问你的DW1820A驱动了吗

### ISSUE THREAD

**Issue by gooff327** [Jxh98/ESC-B360H4-MI#1]
你好, 我也买了一块DW1820A, 但是驱动后wifi 只能2.4G 蓝牙更是连接秒断, 蓝牙的固件版本是v7 c4689

**Comment by Jxh98** [comment]
[DW1820A/BCM94350ZAE/BCM94356ZEPA50DX插入的正确姿势](https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html)

**Comment by gooff327** [comment]
嗯 我就是根据这个来的 , 但是现在就是蓝牙连接秒断 wifi没有5G, 请问你的完美吗?

**Comment by Jxh98** [comment]
> 嗯 我就是根据这个来的 , 但是现在就是蓝牙连接秒断 wifi没有5G, 请问你的完美吗?

屏蔽 针脚 试试
